# netlify.toml — minimal + solid

[build]
  # If your Builder export lives elsewhere, change "site" to that folder.
  publish   = "site"
  functions = "functions"

[functions]
  node_bundler = "esbuild"

# Allow calling functions from the browser (CORS)
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin  = "*"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "*"

# Optional sugar: /api/... -> /.netlify/functions/...
[[redirects]]
  from = "/api/*"
  to   = "/.netlify/functions/:splat"
  status = 200
